Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Pedro Henrique dos Santos santana
// Data atual  : 28/03/2023
Var
// Seção de Declarações das variáveis 
nota:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("qual a sua nota")
leia(nota)
se(nota>=6)entao
escreval("voce foi aprovado")
senao
 escreval("voce esta reprovado")
fimse
Fimalgoritmo