Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Pedro Henrinque dos Santos Santana
// Data atual  : 28/03/2023
Var
// Seção de Declarações das variáveis 
ph:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval(" qual e o ph da agua")
leia(ph)
se (ph<=7) entao
escreval("o ph esta baixo")
senao
escreval("o ph esta alto")
fimse
fimalgoritmo





































